# Generated by Django 3.2.8 on 2022-09-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cat_id',
        ),
    ]
